name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update
        
      - uses: Swatinem/rust-cache@v2
      
      - name: Run tests
        run: |
          cargo check
          cargo test --verbose
